apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "earthly-buildkit-chart.fullname" . }}
  labels:
    {{- include "earthly-buildkit-chart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "earthly-buildkit-chart.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "earthly-buildkit-chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "earthly-buildkit-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/usr/bin/entrypoint.sh", "buildkitd", "--config=/etc/buildkitd.toml", "--debugaddr=127.0.0.1:8054"]
          env:
            - name: BUILDKIT_TCP_TRANSPORT_ENABLED
              value: "true"
            - name: BUILDKIT_TLS_ENABLED
              value: "false"
            - name: EARTHLY_SKIP_CGROUP_SETUP
              value: "true"
            - name: CACHE_SIZE_MB
              value: "45000"
            # - name: BUILDKIT_SCHEDULER_DEBUG
            #   value: "1"
            # - name: BUILDKIT_DEBUG
            #   value: "true"
            
          ports:
            - name: buildkit
              containerPort: 8372
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: earthly-cache
              mountPath: /tmp/earthly
              readOnly: false
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: earthly-cache
          persistentVolumeClaim:
            claimName: "pvc-{{ .Release.Name }}"
      {{- end }}
